name: MinecraftNew
version: '${project.version}'
main: goat.minecraft.minecraftnew.MinecraftNew
api-version: '1.20'
permissions:
  continuity.use:
    description: "Allows the player to use the main feature of Continuity"
    default: true  # true = granted to everyone by default
  continuity.admin:
    description: "Grants admin access to Continuity"
    default: op     # op = only given to server operators (OPs) by default
commands:
  merits:
    description: Open the merits GUI
  grantmerit:
    description: Grants a merit point to a player
    usage: /grantmerit <playerName>
  resetend:
    description: Resets The End dimension.
    usage: /resetend
  end:
    description: Teleports the player to The End.
    usage: /end
  nether:
    description: Teleports the player to The Nether.
    usage: /nether
  overworld:
    description: Teleports the player to The Overworld.
    usage: /overworld
  testskill:
    description: "Simulates a level-up message for testing."
  removeinvisiblestands:
    description: Removes all invisible armor stands from the server.
    usage: /removeinvisiblestands
  recipes:
    description: List all custom recipes in chat
  viewrecipe:
    description: Opens a GUI showing a particular recipe
  collection:
    description: lol
  hostility:
    description: opens difficulty GUI.
  spawnseacreature:
    description: Spawns a sea creature by name.
  givecustomitem:
    description: Gives a predefined custom item to the player.
    usage: /givecustomitem <customitem>
    permission: givecustomitem.use
  villager:
    description: Summon a villager with no AI
  xp:
    description: Manage player XP for different skills
    usage: /xp <add|subtract|set|get> <player> <skill> [amount]
    permission: myplugin.xp
    permission-message: You do not have permission to use this command.
  loadsubsystems:
    description: lol
  skills:
    description: lol
  coins:
    description: lol
  clearpets:
    description: Clears a player's pets.
    usage: /<command> [player]
  givegenerator:
    description: lol
  getpet:
    description: lol
  pet:
    description: Opens the pet GUI.
    default: true
  setpetlevel:
    description: Set a pet to level 100.
    usage: /setpetlevel <petName>
  forcebloodmoon:
    description: Forces a Blood Moon to rise.
