name: MinecraftNew
version: '${project.version}'
main: goat.minecraft.minecraftnew.MinecraftNew
api-version: '1.21'
depend: [Citizens]
softdepend:
  - WorldEdit
permissions:
  continuity.use:
    description: "Allows the player to use the main feature of Continuity"
    default: true  # true = granted to everyone by default
  continuity.admin:
    description: "Grants admin access to Continuity"
    default: op     # op = only given to server operators (OPs) by default
commands:
  debugplayer:
    description: Spawns a hostile player NPC that attacks the sender
    usage: /debugplayer
  getculinaryrecipe:
    description: Gives you the crafted output for a culinary recipe.
    usage: /getculinaryrecipe <recipe name>
  regenerate:
    description: Re-draws the region map in the tropic world.
  pasteSchem:
    description: Paste a .schem from your jar at your location
    usage: /pasteSchem <name>
  tropic:
    description: Create or reload the single-island ocean world.
    usage: /<command>
  frozen:
    description: Create or reload the frozen island world.
    usage: /<command>
  decomission:
    description: Unload & delete the tropic world.
    usage: /<command>
  defrost:
    description: Unload & delete the frozen world.
    usage: /<command>
  setplayeroxygen:
    description: Admin command to set the durability of a player's held item
    permission: continuity.admin
  setdurability:
    description: Admin command to set the durability of a player's held item
    usage: /setdurability <player> <durability>
    permission: continuity.admin
  setcustomdurability:
    description: Sets custom durability values on the held item
    usage: /setcustomdurability <current> <max>
    permission: continuity.admin
  addgoldendurability:
    description: Sets Golden Durability on the held item
    usage: /addgoldendurability <amount>
    permission: continuity.admin
  forceworkcycle:
    description: Forces the villager work cycle timer to 1 second.
    usage: /<command>
  testdragon:
      description: Summon the initial and strong dragons in the End for testing.
      usage: /testdragon
  skin:
    description: Applies a skin name to the item in your hand.
  island:
    description: teleports you to the island.
  testpet:
    description: Adds a pet to the player’s collection for testing.
    usage: /testpet <petName>
  discs:
    description: Opens the music discs information GUI.
  merits:
    description: Open the merits GUI
  grantmerit:
    description: Grants a merit point to a player
    usage: /grantmerit <playerName>
  grantGhostPet:
    description: Grants the Ghost pet to a player
    usage: /grantGhostPet <player>
  resetend:
    description: Resets The End dimension.
    usage: /resetend
  refreshend:
    description: Respawns a fresh dragon in The End.
    usage: /refreshEnd
    permission: continuity.admin
  end:
    description: Teleports the player to The End.
    usage: /end
  nether:
    description: Teleports the player to The Nether.
    usage: /nether
  overworld:
    description: Teleports the player to The Overworld.
    usage: /overworld
  testskill:
    description: "Simulates a level-up message for testing."
  removeinvisiblestands:
    description: Removes all invisible armor stands from the server.
    usage: /removeinvisiblestands
  recipes:
    description: List all custom recipes in chat
  viewrecipe:
    description: Opens a GUI showing a particular recipe
  spawnseacreature:
    description: Spawns a sea creature by name.
    permission: continuity.admin
  spawncorpse:
    description: Spawns a corpse by name.
    permission: continuity.admin
  givecustomitem:
    description: Gives a predefined custom item to the player.
    usage: /givecustomitem <customitem>
    permission: givecustomitem.use
  i:
    description: Gives a predefined custom item to the player.
    usage: /i <item_name> [amount]
    permission: continuity.admin
  villager:
    description: Summon a villager with no AI
  xp:
    description: Manage player XP for different skills
    usage: /xp <add|subtract|set|get> <player> <skill> [amount]
    permission: myplugin.xp
    permission-message: You do not have permission to use this command.
  loadsubsystems:
    description: lol
  skills:
    description: lol
  coins:
    description: lol
  clearpets:
    description: Clears a player's pets.
    usage: /<command> [player]
  givegenerator:
    description: lol
  getpet:
    description: lol
  pets:
    description: Opens the pet GUI.
    default: true
  setpetlevel:
    description: Set a pet to level 100.
    usage: /setpetlevel <petName>
  combatreload:
    description: Reloads the combat subsystem configuration
    usage: /combatreload
    permission: continuity.admin
  setbeaconpower:
    description: Sets the power of a Beacon Charm in your hand
    usage: /setbeaconpower <power>
    permission: continuity.admin
  generatecontinuityisland:
    description: Installs the Continuity Island world from resources
    usage: /generatecontinuityisland
    permission: continuity.admin
  continuitytp:
    description: Teleports player to the Continuity Island world
    usage: /continuitytp
    permission: continuity.use
  clearlava:
    description: Clears all lava blocks in a 64x64 area around the player
    usage: /clearlava
    permission: continuity.admin
  repair:
    description: Repairs the held item to full durability
    usage: /repair
    permission: continuity.admin
  repairall:
    description: Repairs all durable items in your inventory to full durability
    usage: /repairall
    permission: continuity.admin
  finishbrews:
    description: Sets all active brews to finish in one second
    usage: /finishbrews
    permission: continuity.admin
  setreforgeseconds:
    description: Sets reforge timers to the provided seconds
    usage: /setreforgeseconds <seconds>
    permission: continuity.admin
  setsaplingcooldownsecondsremaining:
    description: Sets sapling cooldown seconds remaining
    usage: /setsaplingcooldownsecondsremaining <seconds>
    permission: continuity.admin
  openvillagertrademenu:
    description: Opens a villager trade menu for testing
    usage: /openVillagerTradeMenu <profession> <tier>
    permission: continuity.admin
  togglecustomenchantments:
    description: Toggle your custom enchantments on or off
    usage: /togglecustomenchantments
    default: true
  togglepotioneffects:
    description: Toggle your custom potion effects on or off
    usage: /togglepotioneffects
    default: true
  togglebars:
    description: Toggle bar display on your Environment sidebar
    usage: /togglebars
    default: true
  setskilllevel:
    description: Sets a player's skill level
    usage: /setskilllevel <player> <skill> <level>
    permission: continuity.admin
  addtalentpoint:
    description: Gives talent points to a player
    usage: /addTalentPoint <player> <skill> <amount>
    permission: continuity.admin
  grantLegacyTaming:
    description: Grants Taming XP based on existing pets
    usage: /grantLegacyTaming <player>
    permission: continuity.admin
  getnearestcatalysttype:
    description: Gets the nearest catalyst type in range of the player
    usage: /getnearestcatalysttype
    permission: continuity.admin
  warp:
    description: Teleports the player to the specified world
    usage: /warp <worldname>
    permission: continuity.admin
  simulate:
    description: Start a Blood Moon assault
    usage: /simulate
    permission: continuity.admin
  skip:
    description: Skip the assault rest period
    usage: /skip
    default: true
  getstructureblock:
    description: Gives a Structure Block Charm with zero power
    usage: /getstructureblock
    permission: continuity.admin
  setstructureblockpower:
    description: Sets the power of a Structure Block Charm in your hand
    usage: /setstructureblockpower <power>
    permission: continuity.admin
  previewparticle:
    description: Shows a particle effect around the player until they move
    usage: /previewparticle <particle> <style> <count> <frequency>
    permission: continuity.admin
    aliases:
      - preview_particle
  previewflow:
    description: Shows flow entities spinning around the player
    usage: /previewflow <flow> <intensity>
    permission: continuity.admin
  previewauratemplate:
    description: Shows an aura effect using a template
    usage: /previewauratemplate <name>
    permission: continuity.admin
  aura:
    description: Toggles display of your active aura
    usage: /aura
    default: true
  flowdebug:
    description: Shows a player's current flow level
    usage: /flowdebug
    permission: continuity.admin
  seacreaturechance:
    description: Displays your total Sea Creature Chance
    usage: /seacreaturechance
    default: true
  treasurechance:
    description: Displays your total Treasure Chance
    usage: /treasurechance
    default: true
  spiritchance:
    description: Displays your total Spirit Chance
    usage: /spiritchance
    default: true
  stats:
    description: Shows a GUI of your overall stats
    usage: /stats
    default: true
  stripreforge:
    description: Removes the reforge from the item in your hand
    usage: /stripreforge
    permission: continuity.admin
  applyreforge:
    description: Applies a reforge to the item in your hand
    usage: /applyreforge <reforgename> <rarity>
    permission: continuity.admin
  setamount:
    description: Sets the amount of the item in your hand
    usage: /setamount <amount>
    permission: continuity.admin
  nutrients:
    description: View your nutrition levels
    usage: /nutrients
    default: true
  redvignette:
    description: Shows a red vignette overlay using the world border
    usage: /redvignette [seconds]
    permission: continuity.admin
  glowingores:
    description: Highlights nearby ores with a colored glow
    usage: /glowingores <seconds>
    permission: continuity.admin
