name: MinecraftNew
version: '${project.version}'
main: goat.minecraft.minecraftnew.MinecraftNew
api-version: '1.20'
softdepend:
  - WorldEdit
permissions:
  continuity.use:
    description: "Allows the player to use the main feature of Continuity"
    default: true  # true = granted to everyone by default
  continuity.admin:
    description: "Grants admin access to Continuity"
    default: op     # op = only given to server operators (OPs) by default
commands:
  getculinaryrecipe:
    description: Gives you the crafted output for a culinary recipe.
    usage: /getculinaryrecipe <recipe name>
  regenerate:
    description: Re-draws the region map in the tropic world.
  pasteSchem:
    description: Paste a .schem from your jar at your location
    usage: /pasteSchem <name>
  tropic:
    description: Create or reload the single-island ocean world.
    usage: /<command>
  decomission:
    description: Unload & delete the tropic world.
    usage: /<command>
  setplayeroxygen:
    description: Admin command to set the durability of a player's held item
    permission: continuity.admin
  setdurability:
    description: Admin command to set the durability of a player's held item
    usage: /setdurability <player> <durability>
    permission: continuity.admin
  forceworkcycle:
    description: Forces the villager work cycle timer to 1 second.
    usage: /<command>
  testdragon:
      description: Summon the initial and strong dragons in the End for testing.
      usage: /testdragon
  skin:
    description: Applies a skin name to the item in your hand.
  island:
    description: teleports you to the island.
  testpet:
    description: Adds a pet to the player’s collection for testing.
    usage: /testpet <petName>
  discs:
    description: Opens the music discs information GUI.
  merits:
    description: Open the merits GUI
  grantmerit:
    description: Grants a merit point to a player
    usage: /grantmerit <playerName>
  resetend:
    description: Resets The End dimension.
    usage: /resetend
  end:
    description: Teleports the player to The End.
    usage: /end
  nether:
    description: Teleports the player to The Nether.
    usage: /nether
  overworld:
    description: Teleports the player to The Overworld.
    usage: /overworld
  testskill:
    description: "Simulates a level-up message for testing."
  removeinvisiblestands:
    description: Removes all invisible armor stands from the server.
    usage: /removeinvisiblestands
  recipes:
    description: List all custom recipes in chat
  viewrecipe:
    description: Opens a GUI showing a particular recipe
  hostility:
    description: opens difficulty GUI.
  spawnseacreature:
    description: Spawns a sea creature by name.
  givecustomitem:
    description: Gives a predefined custom item to the player.
    usage: /givecustomitem <customitem>
    permission: givecustomitem.use
  villager:
    description: Summon a villager with no AI
  xp:
    description: Manage player XP for different skills
    usage: /xp <add|subtract|set|get> <player> <skill> [amount]
    permission: myplugin.xp
    permission-message: You do not have permission to use this command.
  loadsubsystems:
    description: lol
  skills:
    description: lol
  coins:
    description: lol
  clearpets:
    description: Clears a player's pets.
    usage: /<command> [player]
  givegenerator:
    description: lol
  getpet:
    description: lol
  pet:
    description: Opens the pet GUI.
    default: true
  setpetlevel:
    description: Set a pet to level 100.
    usage: /setpetlevel <petName>
  forcebloodmoon:
    description: Forces a Blood Moon to rise.
  combatreload:
    description: Reloads the combat subsystem configuration
    usage: /combatreload
    permission: continuity.admin
  generatecontinuityisland:
    description: Installs the Continuity Island world from resources
    usage: /generatecontinuityisland
    permission: continuity.admin
  continuitytp:
    description: Teleports player to the Continuity Island world
    usage: /continuitytp
    permission: continuity.use
  clearlava:
    description: Clears all lava blocks in a 64x64 area around the player
    usage: /clearlava
    permission: continuity.admin
  repair:
    description: Repairs the held item to full durability
    usage: /repair
    permission: continuity.admin
  setskilllevel:
    description: Sets a player's skill level
    usage: /setskilllevel <player> <skill> <level>
    permission: continuity.admin
  beaconcharm:
    description: Opens the Beacon Catalyst GUI
    usage: /beaconcharm [tier]
    permission: continuity.use
